"""
NaliBot Setup — run this once before anything else.
Checks Python, installs packages, collects your credentials, trains the ML model.
"""

import sys, os, subprocess

def banner(msg):
    print(f"\n{'='*55}")
    print(f"  {msg}")
    print(f"{'='*55}")

def ask(prompt, secret=False):
    import getpass
    try:
        val = getpass.getpass(f"  {prompt}: ") if secret else input(f"  {prompt}: ")
        return val.strip()
    except (EOFError, KeyboardInterrupt):
        print("\nSetup cancelled.")
        sys.exit(0)

# ── 1. Python version ─────────────────────────────────────────────────────────
banner("Step 1: Checking Python version")
major, minor = sys.version_info[:2]
print(f"  Python {major}.{minor} detected")
if major < 3 or minor < 10:
    print("  ERROR: NaliBot requires Python 3.10 or newer.")
    print("  Download it from: https://www.python.org/downloads/")
    sys.exit(1)
print("  OK")

# ── 2. Install packages ───────────────────────────────────────────────────────
banner("Step 2: Installing required packages")
req_file = os.path.join(os.path.dirname(__file__), "requirements.txt")
result = subprocess.run(
    [sys.executable, "-m", "pip", "install", "-r", req_file, "-q"],
    capture_output=True, text=True
)
if result.returncode != 0:
    print(f"  ERROR installing packages:\n{result.stderr}")
    sys.exit(1)
print("  All packages installed.")

# ── 3. Check Node.js for dashboard ───────────────────────────────────────────
banner("Step 3: Checking Node.js (for dashboard)")
node_check = subprocess.run(["node", "--version"], capture_output=True, text=True)
if node_check.returncode != 0:
    print("  WARNING: Node.js not found. The dashboard won't work.")
    print("  Download from: https://nodejs.org  (LTS version)")
    print("  You can still run the bot without the dashboard.")
    input("  Press Enter to continue anyway...")
else:
    print(f"  Node.js {node_check.stdout.strip()} found. OK")
    dashboard_dir = os.path.join(os.path.dirname(__file__), "ai-trading-bot")
    print("  Installing dashboard packages (this may take a minute)...")
    subprocess.run(["npm", "install", "--silent"], cwd=dashboard_dir,
                   capture_output=True)
    print("  Dashboard ready.")

# ── 4. Credentials ────────────────────────────────────────────────────────────
banner("Step 4: Setting up your credentials")

env_path = os.path.join(os.path.dirname(__file__), "config", "production.env")
os.makedirs(os.path.dirname(env_path), exist_ok=True)

# Read existing env so we don't wipe anything
existing = {}
if os.path.exists(env_path):
    from dotenv import dotenv_values
    existing = dotenv_values(env_path)

def need(key):
    val = existing.get(key, "")
    return not val or "your_" in val or len(val) < 5

print("""
  You'll need two things:

  A) Kraken API key & secret — for live XRP price data
     Get them free at: kraken.com → Settings → API → Create Key
     Permissions needed: Query Funds, Query Orders (read-only is fine for paper trading)

  B) Telegram bot token & chat ID — for trade alerts on your phone
     - Message @BotFather on Telegram → /newbot → follow steps → copy the token
     - Message @userinfobot on Telegram → it replies with your chat ID number
""")

print("  (Press Enter to keep any existing value shown in brackets)\n")

def prompt_credential(key, label, is_secret=False):
    current = existing.get(key, "")
    safe_current = f"...{current[-6:]}" if current and len(current) > 6 else current
    display = f"{label} [{safe_current}]" if current else label
    val = ask(display, secret=is_secret)
    return val if val else current

kraken_key    = prompt_credential("KRAKEN_API_KEY",    "Kraken API Key",    is_secret=True)
kraken_secret = prompt_credential("KRAKEN_API_SECRET", "Kraken API Secret", is_secret=True)
tg_token      = prompt_credential("TELEGRAM_BOT_TOKEN", "Telegram Bot Token", is_secret=True)
tg_chat       = prompt_credential("TELEGRAM_CHAT_ID",   "Telegram Chat ID")

# Test Telegram immediately
if tg_token and tg_chat:
    print("\n  Testing Telegram...")
    try:
        import requests
        r = requests.post(
            f"https://api.telegram.org/bot{tg_token}/sendMessage",
            json={"chat_id": tg_chat, "text": "NaliBot connected! Setup complete."},
            timeout=8
        )
        if r.json().get("ok"):
            print("  Telegram test message sent! Check your phone.")
        else:
            print(f"  Telegram test failed: {r.json().get('description')}")
            print("  Double-check your token and chat ID.")
    except Exception as e:
        print(f"  Telegram test error: {e}")

# Write env file
with open(env_path, "w") as f:
    f.write(f"""# NaliBot Production Config — auto-generated by setup.py
KRAKEN_API_KEY={kraken_key}
KRAKEN_API_SECRET={kraken_secret}
TELEGRAM_BOT_TOKEN={tg_token}
TELEGRAM_CHAT_ID={tg_chat}

INITIAL_BALANCE=1000
MAX_DRAWDOWN_PERCENTAGE=20
RISK_PER_TRADE_PERCENTAGE=8
MAX_DAILY_LOSS_PERCENTAGE=15
TRADING_PAIRS=XRP/USD,XRP/USDT
NODE_ENV=production
""")
print("\n  Credentials saved.")

# ── 5. Train ML model ─────────────────────────────────────────────────────────
banner("Step 5: Training the ML model (pulls ~20 days of XRP data)")
print("  This takes about 2 minutes...\n")
train_script = os.path.join(os.path.dirname(__file__), "train_model.py")
result = subprocess.run(
    [sys.executable, "-X", "utf8", train_script],
    text=True
)
if result.returncode != 0:
    print("  WARNING: Model training failed. Bot will run with rule-based signals only.")
else:
    print("\n  ML model ready.")

# ── Done ──────────────────────────────────────────────────────────────────────
banner("Setup complete!")
print("""
  To start the bot + dashboard, run:

      python start.py

  That's it. The dashboard will open in your browser automatically.
""")
