/**
 * Read-Only Operator API: Confidence Report
 * 
 * PHASE 10: Confidence Accumulation & Coverage
 * 
 * Exposes confidence reports for operator viewing.
 * READ-ONLY - No execution, no writes, no governance bypass.
 */

import { NextApiRequest, NextApiResponse } from 'next';
import * as fs from 'fs';
import * as path from 'path';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed - read-only API' });
  }

  try {
    const { date, format } = req.query;
    
    // Reports are stored in reports/ directory
    const reportsDir = path.join(process.cwd(), 'reports');
    
    if (!fs.existsSync(reportsDir)) {
      return res.status(404).json({
        error: 'No reports directory found',
        message: 'Confidence reports are generated by running the accumulation script',
        hint: 'Run: ts-node scripts/run-confidence-accumulation.ts'
      });
    }

    // Get report for specific date
    if (date && typeof date === 'string') {
      const jsonPath = path.join(reportsDir, `confidence-report-${date}.json`);
      const textPath = path.join(reportsDir, `confidence-report-${date}.txt`);
      
      if (fs.existsSync(jsonPath)) {
        const reportData = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
        
        // Return in requested format
        if (format === 'text') {
          if (fs.existsSync(textPath)) {
            const textReport = fs.readFileSync(textPath, 'utf8');
            return res.status(200).setHeader('Content-Type', 'text/plain').send(textReport);
          }
        }
        
        return res.status(200).json({
          success: true,
          report: reportData,
          date
        });
      } else {
        return res.status(404).json({
          error: 'Report not found',
          date,
          hint: 'Reports are generated daily by the accumulation script'
        });
      }
    }

    // List all available reports
    const files = fs.readdirSync(reportsDir);
    const reportFiles = files
      .filter(f => f.startsWith('confidence-report-') && f.endsWith('.json'))
      .map(f => {
        const dateMatch = f.match(/confidence-report-(.+)\.json/);
        return dateMatch ? dateMatch[1] : null;
      })
      .filter(d => d !== null)
      .sort()
      .reverse(); // Most recent first

    if (reportFiles.length === 0) {
      return res.status(404).json({
        error: 'No confidence reports found',
        message: 'Confidence reports are generated by running the accumulation script',
        hint: 'Run: ts-node scripts/run-confidence-accumulation.ts'
      });
    }

    // Return most recent report by default
    const mostRecentDate = reportFiles[0];
    const mostRecentPath = path.join(reportsDir, `confidence-report-${mostRecentDate}.json`);
    const reportData = JSON.parse(fs.readFileSync(mostRecentPath, 'utf8'));

    return res.status(200).json({
      success: true,
      report: reportData,
      availableDates: reportFiles,
      mostRecent: mostRecentDate
    });

  } catch (error: any) {
    console.error('[CONFIDENCE_REPORT_API] Error:', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: error.message
    });
  }
}
